import unittest

import sklearn.preprocessing  # To get rid of ImportWarning

from lambdo.Workflow import *

#
# Train functions for testing
#
def transform_func_1(value, model_param):  # It consumes model generated by the training function
    return value + model_param

def train_func_1(value):  # Retrun constant model (no data is needed to train it)
    trained_model = {"model_param": 1.0}
    return trained_model

class TrainTestCase(unittest.TestCase):

    def setUp(self):
        pass

    def test_train(self):
        wf_json = {
            "id": "My workflow",
            "tables": [
                {
                    "id": "My table",
                    "columns": [
                        {
                            "id": "My column",
                            "function": "test_train:transform_func_1",
                            "scope": "one",
                            "inputs": ["A"],
                            "train": {
                                "function": "test_train:train_func_1",
                                "outputs": []
                            }
                        }
                    ]
                }
            ]
        }
        wf = Workflow(wf_json)

        # Provide data directly (without table population)
        data = {'A': [1, 2, 3]}
        df = pd.DataFrame(data)
        tb = wf.tables[0]
        tb.data = df

        wf.execute()

        self.assertAlmostEqual(wf.tables[0].data['My column'][0], 2.0)
        self.assertAlmostEqual(wf.tables[0].data['My column'][1], 3.0)
        self.assertAlmostEqual(wf.tables[0].data['My column'][2], 4.0)

if __name__ == '__main__':
    unittest.main()
